version: '3.1'

services:

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sales_system
    ports:
      - '3002:5432'